GET http://localhost:5000/deck

#####

GET http://localhost:5000/deck/21a35aed-e26f-488e-8aef-7c8293931e4b

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "FULL",
    "shuffled": false
}

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "FULL",
    "shuffled": true
}

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "SHORT",
    "shuffled": false
}

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "SHORT",
    "shuffled": true
}