GET http://localhost:5000/deck

#####

GET http://localhost:5000/deck/22833b92-4719-4c90-a351-e0f942863419

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "FULL",
    "shuffled": false
}


####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "FULL",
    "shuffled": true
}

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "SHORT",
    "shuffled": false
}

####

POST http://localhost:5000/deck
Content-Type: application/json

{
    "type": "SHORT",
    "shuffled": true
}

####
POST http://localhost:5000/deck/draw/22833b92-4719-4c90-a351-e0f942863419?count=3